In [9]:
import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta

np.random.seed(42)

base_date = datetime(2024, 1, 1)
devices = ["Desktop", "Mobile", "Tablet"]
referrers = ["Google", "Direct", "Social", "Email", "Referral"]

data = []
for i in range(1000):
    session_id = f"SESS{i+1}"
    user_id = f"USER{random.randint(1, 200)}" if random.random() > 0.05 else ""
    timestamp = base_date + timedelta(seconds=random.randint(0, 30*24*60*60))  # 30 days
    date_format = random.choice(["%Y-%m-%d %H:%M:%S", "%m/%d/%Y %H:%M:%S"])
    timestamp = timestamp.strftime(date_format) if random.random() > 0.02 else "2024-13-01 10:00:00"
    page_url = random.choice(["home", "pricing", "blog", "signup"]) if random.random() > 0.1 else "http:/page"
    referrer = random.choice(referrers) if random.random() > 0.1 else ""
    device = random.choice(devices)
    time_on_page = random.uniform(-10, 300) if random.random() > 0.05 else random.choice(["ten", "zero"])
    bounce = random.choice(["Yes", "No", "Y", "N"]) if random.random() > 0.08 else ""

    data.append([session_id, user_id, timestamp, page_url, referrer, device, time_on_page, bounce])

df = pd.DataFrame(data, columns=["SessionID", "UserID", "Timestamp", "PageURL", 
                                 "Referrer", "DeviceType", "TimeOnPage", "Bounce"])
df.to_csv("website_analytics.csv", index=False)
print("Saved as 'website_analytics.csv'")

Saved as 'website_analytics.csv'

In [10]:
df.head()

,SessionID,UserID,Timestamp,PageURL,Referrer,DeviceType,TimeOnPage,Bounce
0,SESS1,USER156,2024-01-13 11:30:06,home,Direct,Desktop,60.980094,Y
1,SESS2,USER79,01/11/2024 12:39:29,signup,Direct,Tablet,zero,No
2,SESS3,USER51,01/30/2024 07:05:02,home,Social,Desktop,161.731727,No
3,SESS4,USER113,01/06/2024 03:20:11,blog,Direct,Desktop,246.335906,Yes
4,SESS5,USER143,01/25/2024 11:29:49,pricing,Email,Tablet,281.733425,Yes

In [11]:
df_clean = df
df_clean.head()

,SessionID,UserID,Timestamp,PageURL,Referrer,DeviceType,TimeOnPage,Bounce
0,SESS1,USER156,2024-01-13 11:30:06,home,Direct,Desktop,60.980094,Y
1,SESS2,USER79,01/11/2024 12:39:29,signup,Direct,Tablet,zero,No
2,SESS3,USER51,01/30/2024 07:05:02,home,Social,Desktop,161.731727,No
3,SESS4,USER113,01/06/2024 03:20:11,blog,Direct,Desktop,246.335906,Yes
4,SESS5,USER143,01/25/2024 11:29:49,pricing,Email,Tablet,281.733425,Yes

In [63]:
df_clean['TimestampOrginal'] = df_clean['Timestamp']
df_clean

,SessionID,UserID,Timestamp,PageURL,Referrer,DeviceType,TimeOnPage,Bounce,TimestampOrginal
0,SESS1,USER156,2024-01-13 11:30:06,home,Direct,Desktop,60.980094,Yes,2024-01-13 11:30:06
1,SESS2,USER79,01/11/2024 12:39:29,signup,Direct,Tablet,0.000000,No,01/11/2024 12:39:29
2,SESS3,USER51,01/30/2024 07:05:02,home,Social,Desktop,161.731727,No,01/30/2024 07:05:02
3,SESS4,USER113,01/06/2024 03:20:11,blog,Direct,Desktop,246.335906,Yes,01/06/2024 03:20:11
4,SESS5,USER143,01/25/2024 11:29:49,pricing,Email,Tablet,281.733425,Yes,01/25/2024 11:29:49
...,...,...,...,...,...,...,...,...,...
885,SESS995,USER5,2024-01-26 19:17:54,home,Direct,Mobile,209.598001,No,2024-01-26 19:17:54
886,SESS997,USER175,01/24/2024 05:00:10,signup,Referral,Desktop,99.814326,No,01/24/2024 05:00:10
887,SESS998,USER10,01/21/2024 12:54:50,home,Referral,Desktop,49.497936,No,01/21/2024 12:54:50
888,SESS999,USER65,01/23/2024 16:39:13,blog,Social,Mobile,0.000000,Yes,01/23/2024 16:39:13
889,SESS1000,USER13,01/19/2024 01:57:21,home,Google,Desktop,272.061808,Yes,01/19/2024 01:57:21

In [65]:
df_clean['Timestamp'] = pd.to_datetime(df_clean['Timestamp'], errors='coerce')
df_clean['Timestamp']

0     2024-01-13 11:30:06
1     2024-01-11 12:39:29
2     2024-01-30 07:05:02
3     2024-01-06 03:20:11
4     2024-01-25 11:29:49
              ...
885   2024-01-26 19:17:54
886   2024-01-24 05:00:10
887   2024-01-21 12:54:50
888   2024-01-23 16:39:13
889   2024-01-19 01:57:21
Name: Timestamp, Length: 890, dtype: datetime64[ns]

In [67]:
df_clean['Timestamp'] = df_clean['Timestamp'].dt.strftime('%Y-%m-%d %H:%M:%S')
df_clean

,SessionID,UserID,Timestamp,PageURL,Referrer,DeviceType,TimeOnPage,Bounce,TimestampOrginal
0,SESS1,USER156,2024-01-13 11:30:06,home,Direct,Desktop,60.980094,Yes,2024-01-13 11:30:06
1,SESS2,USER79,2024-01-11 12:39:29,signup,Direct,Tablet,0.000000,No,01/11/2024 12:39:29
2,SESS3,USER51,2024-01-30 07:05:02,home,Social,Desktop,161.731727,No,01/30/2024 07:05:02
3,SESS4,USER113,2024-01-06 03:20:11,blog,Direct,Desktop,246.335906,Yes,01/06/2024 03:20:11
4,SESS5,USER143,2024-01-25 11:29:49,pricing,Email,Tablet,281.733425,Yes,01/25/2024 11:29:49
...,...,...,...,...,...,...,...,...,...
885,SESS995,USER5,2024-01-26 19:17:54,home,Direct,Mobile,209.598001,No,2024-01-26 19:17:54
886,SESS997,USER175,2024-01-24 05:00:10,signup,Referral,Desktop,99.814326,No,01/24/2024 05:00:10
887,SESS998,USER10,2024-01-21 12:54:50,home,Referral,Desktop,49.497936,No,01/21/2024 12:54:50
888,SESS999,USER65,2024-01-23 16:39:13,blog,Social,Mobile,0.000000,Yes,01/23/2024 16:39:13
889,SESS1000,USER13,2024-01-19 01:57:21,home,Google,Desktop,272.061808,Yes,01/19/2024 01:57:21

In [69]:
# df_clean = df_clean.drop(columns=['FormattedTimestamp'])
df_clean

,SessionID,UserID,Timestamp,PageURL,Referrer,DeviceType,TimeOnPage,Bounce,TimestampOrginal
0,SESS1,USER156,2024-01-13 11:30:06,home,Direct,Desktop,60.980094,Yes,2024-01-13 11:30:06
1,SESS2,USER79,2024-01-11 12:39:29,signup,Direct,Tablet,0.000000,No,01/11/2024 12:39:29
2,SESS3,USER51,2024-01-30 07:05:02,home,Social,Desktop,161.731727,No,01/30/2024 07:05:02
3,SESS4,USER113,2024-01-06 03:20:11,blog,Direct,Desktop,246.335906,Yes,01/06/2024 03:20:11
4,SESS5,USER143,2024-01-25 11:29:49,pricing,Email,Tablet,281.733425,Yes,01/25/2024 11:29:49
...,...,...,...,...,...,...,...,...,...
885,SESS995,USER5,2024-01-26 19:17:54,home,Direct,Mobile,209.598001,No,2024-01-26 19:17:54
886,SESS997,USER175,2024-01-24 05:00:10,signup,Referral,Desktop,99.814326,No,01/24/2024 05:00:10
887,SESS998,USER10,2024-01-21 12:54:50,home,Referral,Desktop,49.497936,No,01/21/2024 12:54:50
888,SESS999,USER65,2024-01-23 16:39:13,blog,Social,Mobile,0.000000,Yes,01/23/2024 16:39:13
889,SESS1000,USER13,2024-01-19 01:57:21,home,Google,Desktop,272.061808,Yes,01/19/2024 01:57:21

In [71]:
df_clean['Timestamp'] = df_clean['Timestamp'].where(df_clean['Timestamp'].notna(), df_clean['TimestampOrginal'])
df_clean

,SessionID,UserID,Timestamp,PageURL,Referrer,DeviceType,TimeOnPage,Bounce,TimestampOrginal
0,SESS1,USER156,2024-01-13 11:30:06,home,Direct,Desktop,60.980094,Yes,2024-01-13 11:30:06
1,SESS2,USER79,2024-01-11 12:39:29,signup,Direct,Tablet,0.000000,No,01/11/2024 12:39:29
2,SESS3,USER51,2024-01-30 07:05:02,home,Social,Desktop,161.731727,No,01/30/2024 07:05:02
3,SESS4,USER113,2024-01-06 03:20:11,blog,Direct,Desktop,246.335906,Yes,01/06/2024 03:20:11
4,SESS5,USER143,2024-01-25 11:29:49,pricing,Email,Tablet,281.733425,Yes,01/25/2024 11:29:49
...,...,...,...,...,...,...,...,...,...
885,SESS995,USER5,2024-01-26 19:17:54,home,Direct,Mobile,209.598001,No,2024-01-26 19:17:54
886,SESS997,USER175,2024-01-24 05:00:10,signup,Referral,Desktop,99.814326,No,01/24/2024 05:00:10
887,SESS998,USER10,2024-01-21 12:54:50,home,Referral,Desktop,49.497936,No,01/21/2024 12:54:50
888,SESS999,USER65,2024-01-23 16:39:13,blog,Social,Mobile,0.000000,Yes,01/23/2024 16:39:13
889,SESS1000,USER13,2024-01-19 01:57:21,home,Google,Desktop,272.061808,Yes,01/19/2024 01:57:21

In [73]:
import re

def fix_us_dates(timestamp):
    match = re.match(r'(\d{4})-(\d{2})-(\d{2})\s(\d{2}:\d{2}:\d{2})', timestamp)
    if match:
        year, month, day, time = match.groups()
        if int(month) > 12:
            return f'{year}-{day}-{month} {time}'
        return timestamp

df_clean['Timestamp'] = df_clean['Timestamp'].apply(fix_us_dates)
df_clean['Timestamp'] = pd.to_datetime(df_clean['Timestamp'], errors='coerce')
df_clean

,SessionID,UserID,Timestamp,PageURL,Referrer,DeviceType,TimeOnPage,Bounce,TimestampOrginal
0,SESS1,USER156,2024-01-13 11:30:06,home,Direct,Desktop,60.980094,Yes,2024-01-13 11:30:06
1,SESS2,USER79,2024-01-11 12:39:29,signup,Direct,Tablet,0.000000,No,01/11/2024 12:39:29
2,SESS3,USER51,2024-01-30 07:05:02,home,Social,Desktop,161.731727,No,01/30/2024 07:05:02
3,SESS4,USER113,2024-01-06 03:20:11,blog,Direct,Desktop,246.335906,Yes,01/06/2024 03:20:11
4,SESS5,USER143,2024-01-25 11:29:49,pricing,Email,Tablet,281.733425,Yes,01/25/2024 11:29:49
...,...,...,...,...,...,...,...,...,...
885,SESS995,USER5,2024-01-26 19:17:54,home,Direct,Mobile,209.598001,No,2024-01-26 19:17:54
886,SESS997,USER175,2024-01-24 05:00:10,signup,Referral,Desktop,99.814326,No,01/24/2024 05:00:10
887,SESS998,USER10,2024-01-21 12:54:50,home,Referral,Desktop,49.497936,No,01/21/2024 12:54:50
888,SESS999,USER65,2024-01-23 16:39:13,blog,Social,Mobile,0.000000,Yes,01/23/2024 16:39:13
889,SESS1000,USER13,2024-01-19 01:57:21,home,Google,Desktop,272.061808,Yes,01/19/2024 01:57:21

In [75]:
df_clean['PageURL'].value_counts()

PageURL
pricing    244
blog       222
home       219
signup     205
Name: count, dtype: int64

In [77]:
df_clean = df_clean[~df_clean['PageURL'].str.contains('http:/page', case=False, na=False)].reset_index(drop=True)
df_clean

,SessionID,UserID,Timestamp,PageURL,Referrer,DeviceType,TimeOnPage,Bounce,TimestampOrginal
0,SESS1,USER156,2024-01-13 11:30:06,home,Direct,Desktop,60.980094,Yes,2024-01-13 11:30:06
1,SESS2,USER79,2024-01-11 12:39:29,signup,Direct,Tablet,0.000000,No,01/11/2024 12:39:29
2,SESS3,USER51,2024-01-30 07:05:02,home,Social,Desktop,161.731727,No,01/30/2024 07:05:02
3,SESS4,USER113,2024-01-06 03:20:11,blog,Direct,Desktop,246.335906,Yes,01/06/2024 03:20:11
4,SESS5,USER143,2024-01-25 11:29:49,pricing,Email,Tablet,281.733425,Yes,01/25/2024 11:29:49
...,...,...,...,...,...,...,...,...,...
885,SESS995,USER5,2024-01-26 19:17:54,home,Direct,Mobile,209.598001,No,2024-01-26 19:17:54
886,SESS997,USER175,2024-01-24 05:00:10,signup,Referral,Desktop,99.814326,No,01/24/2024 05:00:10
887,SESS998,USER10,2024-01-21 12:54:50,home,Referral,Desktop,49.497936,No,01/21/2024 12:54:50
888,SESS999,USER65,2024-01-23 16:39:13,blog,Social,Mobile,0.000000,Yes,01/23/2024 16:39:13
889,SESS1000,USER13,2024-01-19 01:57:21,home,Google,Desktop,272.061808,Yes,01/19/2024 01:57:21

In [79]:
df_clean['UserID'] = df_clean['UserID'].replace('', 'Unknow')
df_clean['UserID'].value_counts()

UserID
Unknow     44
USER45     11
USER126    10
USER181     9
USER187     9
           ..
USER138     1
USER1       1
USER19      1
USER148     1
USER38      1
Name: count, Length: 201, dtype: int64

In [81]:
df_clean['Referrer'] = df_clean['Referrer'].replace('', 'Unknow')
df_clean['Referrer'].value_counts()

Referrer
Google      177
Referral    163
Email       158
Direct      154
Social      141
Unknow       97
Name: count, dtype: int64

In [83]:
df_clean

,SessionID,UserID,Timestamp,PageURL,Referrer,DeviceType,TimeOnPage,Bounce,TimestampOrginal
0,SESS1,USER156,2024-01-13 11:30:06,home,Direct,Desktop,60.980094,Yes,2024-01-13 11:30:06
1,SESS2,USER79,2024-01-11 12:39:29,signup,Direct,Tablet,0.000000,No,01/11/2024 12:39:29
2,SESS3,USER51,2024-01-30 07:05:02,home,Social,Desktop,161.731727,No,01/30/2024 07:05:02
3,SESS4,USER113,2024-01-06 03:20:11,blog,Direct,Desktop,246.335906,Yes,01/06/2024 03:20:11
4,SESS5,USER143,2024-01-25 11:29:49,pricing,Email,Tablet,281.733425,Yes,01/25/2024 11:29:49
...,...,...,...,...,...,...,...,...,...
885,SESS995,USER5,2024-01-26 19:17:54,home,Direct,Mobile,209.598001,No,2024-01-26 19:17:54
886,SESS997,USER175,2024-01-24 05:00:10,signup,Referral,Desktop,99.814326,No,01/24/2024 05:00:10
887,SESS998,USER10,2024-01-21 12:54:50,home,Referral,Desktop,49.497936,No,01/21/2024 12:54:50
888,SESS999,USER65,2024-01-23 16:39:13,blog,Social,Mobile,0.000000,Yes,01/23/2024 16:39:13
889,SESS1000,USER13,2024-01-19 01:57:21,home,Google,Desktop,272.061808,Yes,01/19/2024 01:57:21

In [85]:
df_clean['DeviceType'].value_counts()

DeviceType
Tablet     309
Mobile     300
Desktop    281
Name: count, dtype: int64

In [87]:
df_clean['TimeOnPage'].value_counts()

TimeOnPage
0.000000      38
10.000000     19
154.248134     1
296.182580     1
112.183863     1
              ..
268.057314     1
25.040748      1
106.992012     1
283.013682     1
272.061808     1
Name: count, Length: 835, dtype: int64

In [89]:
timeOnPage_Map = {
    'ten': 10,
    'zero': 0
}

df_clean['TimeOnPage'] = pd.to_numeric(df_clean['TimeOnPage'].replace(timeOnPage_Map))
df_clean['TimeOnPage'].value_counts()

TimeOnPage
0.000000      38
10.000000     19
154.248134     1
296.182580     1
112.183863     1
              ..
268.057314     1
25.040748      1
106.992012     1
283.013682     1
272.061808     1
Name: count, Length: 835, dtype: int64

In [91]:
df_clean['TimeOnPage'] = df_clean['TimeOnPage'].where(df_clean['TimeOnPage'] >= 0, 0)
df_clean['TimeOnPage'].describe()

count    890.000000
mean     138.091581
std       91.951990
min        0.000000
25%       57.150885
50%      134.836854
75%      221.340054
max      299.683992
Name: TimeOnPage, dtype: float64

In [93]:
df_clean['Bounce'].value_counts()

Bounce
No     481
Yes    409
Name: count, dtype: int64

In [95]:
Bounce_map = {
    'N': 'No',
    'Y': 'Yes',
    '': 'No'
}

df_clean['Bounce'] = df_clean['Bounce'].replace(Bounce_map)
df_clean['Bounce'].value_counts()

Bounce
No     481
Yes    409
Name: count, dtype: int64

In [109]:
df_clean['Bounce'] = df_clean['Bounce'].mask((df_clean['Bounce'] == 'No') & (df_clean['TimeOnPage'] == 0), 'Yes')
df_clean[df_clean['TimeOnPage'] == 0]

,SessionID,UserID,Timestamp,PageURL,Referrer,DeviceType,TimeOnPage,Bounce,TimestampOrginal
1,SESS2,USER79,2024-01-11 12:39:29,signup,Direct,Tablet,0.0,Yes,01/11/2024 12:39:29
13,SESS16,Unknow,2024-01-05 21:47:12,home,Referral,Desktop,0.0,Yes,01/05/2024 21:47:12
33,SESS39,USER44,2024-01-10 14:43:50,blog,Social,Tablet,0.0,Yes,01/10/2024 14:43:50
41,SESS47,USER94,2024-01-02 13:53:01,home,Referral,Tablet,0.0,Yes,01/02/2024 13:53:01
47,SESS53,USER73,2024-01-22 20:12:30,signup,Direct,Desktop,0.0,Yes,2024-01-22 20:12:30
95,SESS107,USER109,2024-01-03 15:08:52,blog,Google,Desktop,0.0,Yes,2024-01-03 15:08:52
119,SESS133,USER194,2024-01-03 07:37:02,home,Direct,Tablet,0.0,Yes,01/03/2024 07:37:02
128,SESS145,USER176,2024-01-30 14:28:03,home,Google,Desktop,0.0,Yes,2024-01-30 14:28:03
136,SESS155,USER99,2024-01-02 02:27:43,pricing,Social,Desktop,0.0,Yes,01/02/2024 02:27:43
138,SESS158,USER5,2024-01-04 11:29:48,pricing,Direct,Tablet,0.0,Yes,01/04/2024 11:29:48
139,SESS159,USER66,2024-01-16 18:16:23,signup,Google,Tablet,0.0,Yes,2024-01-16 18:16:23
143,SESS164,USER22,2024-01-15 04:44:21,pricing,Referral,Tablet,0.0,Yes,2024-01-15 04:44:21
192,SESS221,USER107,2024-01-22 22:50:42,blog,Direct,Tablet,0.0,Yes,01/22/2024 22:50:42
199,SESS229,USER84,2024-01-04 00:15:12,pricing,Unknow,Mobile,0.0,Yes,01/04/2024 00:15:12
229,SESS261,USER20,2024-01-17 17:28:21,blog,Social,Mobile,0.0,Yes,2024-01-17 17:28:21
294,SESS332,USER25,2024-01-05 07:43:17,home,Email,Tablet,0.0,Yes,2024-01-05 07:43:17
322,SESS365,USER21,2024-01-09 12:55:50,signup,Social,Desktop,0.0,Yes,01/09/2024 12:55:50
360,SESS412,USER157,2024-01-08 08:50:50,pricing,Social,Desktop,0.0,Yes,01/08/2024 08:50:50
361,SESS413,USER49,2024-01-27 17:39:55,signup,Google,Tablet,0.0,Yes,2024-01-27 17:39:55
432,SESS495,USER119,2024-01-14 08:50:51,signup,Social,Tablet,0.0,Yes,2024-01-14 08:50:51
497,SESS570,USER163,2024-01-23 16:20:28,home,Social,Mobile,0.0,Yes,2024-01-23 16:20:28
563,SESS639,USER60,2024-01-22 08:27:56,pricing,Referral,Tablet,0.0,Yes,2024-01-22 08:27:56
600,SESS683,USER72,2024-01-29 06:55:27,home,Referral,Desktop,0.0,Yes,01/29/2024 06:55:27
604,SESS687,USER174,2024-01-04 10:35:57,home,Referral,Mobile,0.0,Yes,2024-01-04 10:35:57
609,SESS692,USER72,2024-01-13 06:28:24,blog,Social,Tablet,0.0,Yes,2024-01-13 06:28:24
629,SESS713,USER100,2024-01-09 02:52:45,home,Email,Desktop,0.0,Yes,01/09/2024 02:52:45
646,SESS731,USER161,2024-01-23 23:52:48,signup,Email,Tablet,0.0,Yes,01/23/2024 23:52:48
669,SESS756,USER28,2024-01-07 21:06:15,blog,Social,Tablet,0.0,Yes,01/07/2024 21:06:15
692,SESS783,USER42,2024-01-16 10:50:14,home,Referral,Tablet,0.0,Yes,2024-01-16 10:50:14
704,SESS796,USER129,2024-01-17 23:23:19,signup,Email,Tablet,0.0,Yes,01/17/2024 23:23:19
705,SESS797,USER154,2024-01-29 10:08:00,home,Social,Desktop,0.0,Yes,2024-01-29 10:08:00
710,SESS803,USER196,2024-01-09 00:54:49,home,Unknow,Mobile,0.0,Yes,2024-01-09 00:54:49
736,SESS832,USER45,2024-01-05 02:05:12,signup,Google,Desktop,0.0,Yes,01/05/2024 02:05:12
740,SESS836,USER3,2024-01-14 00:13:20,home,Email,Desktop,0.0,Yes,2024-01-14 00:13:20
774,SESS872,USER86,2024-01-13 10:00:00,signup,Google,Mobile,0.0,Yes,2024-01-13 10:00:00
836,SESS941,USER142,2024-01-23 20:50:53,signup,Email,Mobile,0.0,Yes,2024-01-23 20:50:53
880,SESS990,USER165,2024-01-02 14:06:17,signup,Google,Mobile,0.0,Yes,01/02/2024 14:06:17
888,SESS999,USER65,2024-01-23 16:39:13,blog,Social,Mobile,0.0,Yes,01/23/2024 16:39:13